name: upload image to docker and then use it in ec2

on:
  push:
    branches:
      - "**"

jobs:
  BuildAndDeployment:
    name: DockerAndEc2
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: actions/checkout@v3

      - name: login to docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: build and push the image for backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: arpitblagan27/githubcd:latest

      - name: build and push the image for frontend
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: arpitblagan27/frontendcd:latest

      - name: check it is pushed or not for backend
        run: docker pull arpitblagan27/githubcd:latest

      - name: check it is pushed or not for frontend
        run: docker pull arpitblagan27/frontendcd:latest
## Don't cram just try to understand
