name: upload image to docker and then use it in ec2

on:
  push:
    branches:
      - "**"

jobs:
  BuildAndDeployment:
    name: DockerAndEc2
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: actions/checkout@v3

      - name: login to docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}
          
      - name: build image
        run: docker build -t bb ./backend/Dockerfile

      - name: build and push the image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: arpitblagan27/githubcd:latest

      - name: check it pushed or not
        run: docker pull arpitblagan27/githubcd:latest
## Don't cram just try to understand
